/* tslint:disable */
/* eslint-disable */
/**
 * E-commerce Assistant API
 * Conversational e-commerce assistant API built with LangChain. Features semantic product search and category browsing with multi-turn memory.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContinueConversationRequestDto
 */
export interface ContinueConversationRequestDto {
    /**
     * Follow-up message in the conversation
     * @type {string}
     * @memberof ContinueConversationRequestDto
     */
    message: string;
}

/**
 * Check if a given object implements the ContinueConversationRequestDto interface.
 */
export function instanceOfContinueConversationRequestDto(value: object): value is ContinueConversationRequestDto {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ContinueConversationRequestDtoFromJSON(json: any): ContinueConversationRequestDto {
    return ContinueConversationRequestDtoFromJSONTyped(json, false);
}

export function ContinueConversationRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContinueConversationRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function ContinueConversationRequestDtoToJSON(json: any): ContinueConversationRequestDto {
    return ContinueConversationRequestDtoToJSONTyped(json, false);
}

export function ContinueConversationRequestDtoToJSONTyped(value?: ContinueConversationRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

