/* tslint:disable */
/* eslint-disable */
/**
 * E-commerce Assistant API
 * Conversational e-commerce assistant API built with LangChain. Features semantic product search and category browsing with multi-turn memory.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConversationResponseDto
 */
export interface ConversationResponseDto {
    /**
     * Assistant summary response
     * @type {string}
     * @memberof ConversationResponseDto
     */
    summary: string;
    /**
     * Retrieved product documents
     * @type {Array<object>}
     * @memberof ConversationResponseDto
     */
    products: Array<object>;
    /**
     * Whether products are included
     * @type {boolean}
     * @memberof ConversationResponseDto
     */
    hasProducts: boolean;
    /**
     * Whether the summary contains Markdown formatting
     * @type {boolean}
     * @memberof ConversationResponseDto
     */
    hasMarkdown: boolean;
    /**
     * Conversation ID
     * @type {string}
     * @memberof ConversationResponseDto
     */
    conversationId: string;
}

/**
 * Check if a given object implements the ConversationResponseDto interface.
 */
export function instanceOfConversationResponseDto(value: object): value is ConversationResponseDto {
    if (!('summary' in value) || value['summary'] === undefined) return false;
    if (!('products' in value) || value['products'] === undefined) return false;
    if (!('hasProducts' in value) || value['hasProducts'] === undefined) return false;
    if (!('hasMarkdown' in value) || value['hasMarkdown'] === undefined) return false;
    if (!('conversationId' in value) || value['conversationId'] === undefined) return false;
    return true;
}

export function ConversationResponseDtoFromJSON(json: any): ConversationResponseDto {
    return ConversationResponseDtoFromJSONTyped(json, false);
}

export function ConversationResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'summary': json['summary'],
        'products': json['products'],
        'hasProducts': json['hasProducts'],
        'hasMarkdown': json['hasMarkdown'],
        'conversationId': json['conversationId'],
    };
}

export function ConversationResponseDtoToJSON(json: any): ConversationResponseDto {
    return ConversationResponseDtoToJSONTyped(json, false);
}

export function ConversationResponseDtoToJSONTyped(value?: ConversationResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'summary': value['summary'],
        'products': value['products'],
        'hasProducts': value['hasProducts'],
        'hasMarkdown': value['hasMarkdown'],
        'conversationId': value['conversationId'],
    };
}

