/* tslint:disable */
/* eslint-disable */
/**
 * E-commerce Assistant API
 * Conversational e-commerce assistant API built with LangChain. Features semantic product search and category browsing with multi-turn memory.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EcommerceAssistantControllerRemoveConversation200Response
 */
export interface EcommerceAssistantControllerRemoveConversation200Response {
    /**
     * 
     * @type {string}
     * @memberof EcommerceAssistantControllerRemoveConversation200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the EcommerceAssistantControllerRemoveConversation200Response interface.
 */
export function instanceOfEcommerceAssistantControllerRemoveConversation200Response(value: object): value is EcommerceAssistantControllerRemoveConversation200Response {
    return true;
}

export function EcommerceAssistantControllerRemoveConversation200ResponseFromJSON(json: any): EcommerceAssistantControllerRemoveConversation200Response {
    return EcommerceAssistantControllerRemoveConversation200ResponseFromJSONTyped(json, false);
}

export function EcommerceAssistantControllerRemoveConversation200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EcommerceAssistantControllerRemoveConversation200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function EcommerceAssistantControllerRemoveConversation200ResponseToJSON(json: any): EcommerceAssistantControllerRemoveConversation200Response {
    return EcommerceAssistantControllerRemoveConversation200ResponseToJSONTyped(json, false);
}

export function EcommerceAssistantControllerRemoveConversation200ResponseToJSONTyped(value?: EcommerceAssistantControllerRemoveConversation200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

