/* tslint:disable */
/* eslint-disable */
/**
 * E-commerce Assistant API
 * Conversational e-commerce assistant API built with LangChain. Features semantic product search and category browsing with multi-turn memory.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewConversationRequestDto
 */
export interface NewConversationRequestDto {
    /**
     * User message to start the conversation
     * @type {string}
     * @memberof NewConversationRequestDto
     */
    message: string;
}

/**
 * Check if a given object implements the NewConversationRequestDto interface.
 */
export function instanceOfNewConversationRequestDto(value: object): value is NewConversationRequestDto {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function NewConversationRequestDtoFromJSON(json: any): NewConversationRequestDto {
    return NewConversationRequestDtoFromJSONTyped(json, false);
}

export function NewConversationRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewConversationRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function NewConversationRequestDtoToJSON(json: any): NewConversationRequestDto {
    return NewConversationRequestDtoToJSONTyped(json, false);
}

export function NewConversationRequestDtoToJSONTyped(value?: NewConversationRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

