/* tslint:disable */
/* eslint-disable */
/**
 * Chat API
 * Multi-turn conversation API built with LangChain and LangGraph. This API maintains conversation history using LangGraph\'s MemorySaver, allowing for contextual multi-turn conversations. The assistant has access to user information tools for personalization.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChatControllerChat400Response,
  ChatControllerChat500Response,
  ChatRequestDto,
  ChatResponseDto,
} from '../models/index';
import {
    ChatControllerChat400ResponseFromJSON,
    ChatControllerChat400ResponseToJSON,
    ChatControllerChat500ResponseFromJSON,
    ChatControllerChat500ResponseToJSON,
    ChatRequestDtoFromJSON,
    ChatRequestDtoToJSON,
    ChatResponseDtoFromJSON,
    ChatResponseDtoToJSON,
} from '../models/index';

export interface ChatControllerChatRequest {
    chatRequestDto: ChatRequestDto;
}

/**
 * ChatApi - interface
 * 
 * @export
 * @interface ChatApiInterface
 */
export interface ChatApiInterface {
    /**
     * Send a message to the AI assistant and receive a response. The conversation is maintained using the conversationId, allowing for multi-turn conversations with context. The assistant has access to user information for personalization.
     * @summary Send a message to the chat assistant
     * @param {ChatRequestDto} chatRequestDto Chat request containing the message, user name, and conversation ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ChatApiInterface
     */
    chatControllerChatRaw(requestParameters: ChatControllerChatRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChatResponseDto>>;

    /**
     * Send a message to the AI assistant and receive a response. The conversation is maintained using the conversationId, allowing for multi-turn conversations with context. The assistant has access to user information for personalization.
     * Send a message to the chat assistant
     */
    chatControllerChat(requestParameters: ChatControllerChatRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChatResponseDto>;

}

/**
 * 
 */
export class ChatApi extends runtime.BaseAPI implements ChatApiInterface {

    /**
     * Send a message to the AI assistant and receive a response. The conversation is maintained using the conversationId, allowing for multi-turn conversations with context. The assistant has access to user information for personalization.
     * Send a message to the chat assistant
     */
    async chatControllerChatRaw(requestParameters: ChatControllerChatRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChatResponseDto>> {
        if (requestParameters['chatRequestDto'] == null) {
            throw new runtime.RequiredError(
                'chatRequestDto',
                'Required parameter "chatRequestDto" was null or undefined when calling chatControllerChat().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/chat`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChatRequestDtoToJSON(requestParameters['chatRequestDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChatResponseDtoFromJSON(jsonValue));
    }

    /**
     * Send a message to the AI assistant and receive a response. The conversation is maintained using the conversationId, allowing for multi-turn conversations with context. The assistant has access to user information for personalization.
     * Send a message to the chat assistant
     */
    async chatControllerChat(requestParameters: ChatControllerChatRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChatResponseDto> {
        const response = await this.chatControllerChatRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
