/* tslint:disable */
/* eslint-disable */
/**
 * Chat API
 * Multi-turn conversation API built with LangChain and LangGraph. This API maintains conversation history using LangGraph\'s MemorySaver, allowing for contextual multi-turn conversations. The assistant has access to user information tools for personalization.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatResponseDto
 */
export interface ChatResponseDto {
    /**
     * The assistant's response message
     * @type {string}
     * @memberof ChatResponseDto
     */
    message: string;
    /**
     * The conversation ID that was used for this exchange
     * @type {string}
     * @memberof ChatResponseDto
     */
    conversationId: string;
    /**
     * Confidence score between 0 and 1 indicating how confident the AI is in its answer
     * @type {number}
     * @memberof ChatResponseDto
     */
    confidence: number;
    /**
     * Indicates whether the response contains Markdown formatting, Mermaid diagrams, or code blocks
     * @type {boolean}
     * @memberof ChatResponseDto
     */
    hasMarkdown: boolean;
}

/**
 * Check if a given object implements the ChatResponseDto interface.
 */
export function instanceOfChatResponseDto(value: object): value is ChatResponseDto {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('conversationId' in value) || value['conversationId'] === undefined) return false;
    if (!('confidence' in value) || value['confidence'] === undefined) return false;
    if (!('hasMarkdown' in value) || value['hasMarkdown'] === undefined) return false;
    return true;
}

export function ChatResponseDtoFromJSON(json: any): ChatResponseDto {
    return ChatResponseDtoFromJSONTyped(json, false);
}

export function ChatResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'conversationId': json['conversationId'],
        'confidence': json['confidence'],
        'hasMarkdown': json['hasMarkdown'],
    };
}

export function ChatResponseDtoToJSON(json: any): ChatResponseDto {
    return ChatResponseDtoToJSONTyped(json, false);
}

export function ChatResponseDtoToJSONTyped(value?: ChatResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'conversationId': value['conversationId'],
        'confidence': value['confidence'],
        'hasMarkdown': value['hasMarkdown'],
    };
}

