/* tslint:disable */
/* eslint-disable */
/**
 * Chat API
 * Multi-turn conversation API built with LangChain and LangGraph. This API maintains conversation history using LangGraph\'s MemorySaver, allowing for contextual multi-turn conversations. The assistant has access to user information tools for personalization.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatControllerRemoveConversation500Response
 */
export interface ChatControllerRemoveConversation500Response {
    /**
     * 
     * @type {number}
     * @memberof ChatControllerRemoveConversation500Response
     */
    statusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof ChatControllerRemoveConversation500Response
     */
    message?: string;
}

/**
 * Check if a given object implements the ChatControllerRemoveConversation500Response interface.
 */
export function instanceOfChatControllerRemoveConversation500Response(value: object): value is ChatControllerRemoveConversation500Response {
    return true;
}

export function ChatControllerRemoveConversation500ResponseFromJSON(json: any): ChatControllerRemoveConversation500Response {
    return ChatControllerRemoveConversation500ResponseFromJSONTyped(json, false);
}

export function ChatControllerRemoveConversation500ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatControllerRemoveConversation500Response {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ChatControllerRemoveConversation500ResponseToJSON(json: any): ChatControllerRemoveConversation500Response {
    return ChatControllerRemoveConversation500ResponseToJSONTyped(json, false);
}

export function ChatControllerRemoveConversation500ResponseToJSONTyped(value?: ChatControllerRemoveConversation500Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusCode': value['statusCode'],
        'message': value['message'],
    };
}

