/* tslint:disable */
/* eslint-disable */
/**
 * Chat API
 * Multi-turn conversation API built with LangChain and LangGraph. This API maintains conversation history using LangGraph\'s MemorySaver, allowing for contextual multi-turn conversations. The assistant has access to user information tools for personalization.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatControllerRemoveConversation400Response
 */
export interface ChatControllerRemoveConversation400Response {
    /**
     * 
     * @type {number}
     * @memberof ChatControllerRemoveConversation400Response
     */
    statusCode?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ChatControllerRemoveConversation400Response
     */
    message?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ChatControllerRemoveConversation400Response
     */
    error?: string;
}

/**
 * Check if a given object implements the ChatControllerRemoveConversation400Response interface.
 */
export function instanceOfChatControllerRemoveConversation400Response(value: object): value is ChatControllerRemoveConversation400Response {
    return true;
}

export function ChatControllerRemoveConversation400ResponseFromJSON(json: any): ChatControllerRemoveConversation400Response {
    return ChatControllerRemoveConversation400ResponseFromJSONTyped(json, false);
}

export function ChatControllerRemoveConversation400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatControllerRemoveConversation400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'message': json['message'] == null ? undefined : json['message'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function ChatControllerRemoveConversation400ResponseToJSON(json: any): ChatControllerRemoveConversation400Response {
    return ChatControllerRemoveConversation400ResponseToJSONTyped(json, false);
}

export function ChatControllerRemoveConversation400ResponseToJSONTyped(value?: ChatControllerRemoveConversation400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusCode': value['statusCode'],
        'message': value['message'],
        'error': value['error'],
    };
}

