/* tslint:disable */
/* eslint-disable */
/**
 * Chat API
 * Multi-turn conversation API built with LangChain and LangGraph. This API maintains conversation history using LangGraph\'s MemorySaver, allowing for contextual multi-turn conversations. The assistant has access to user information tools for personalization.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatControllerRemoveConversation200Response
 */
export interface ChatControllerRemoveConversation200Response {
    /**
     * 
     * @type {string}
     * @memberof ChatControllerRemoveConversation200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the ChatControllerRemoveConversation200Response interface.
 */
export function instanceOfChatControllerRemoveConversation200Response(value: object): value is ChatControllerRemoveConversation200Response {
    return true;
}

export function ChatControllerRemoveConversation200ResponseFromJSON(json: any): ChatControllerRemoveConversation200Response {
    return ChatControllerRemoveConversation200ResponseFromJSONTyped(json, false);
}

export function ChatControllerRemoveConversation200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatControllerRemoveConversation200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ChatControllerRemoveConversation200ResponseToJSON(json: any): ChatControllerRemoveConversation200Response {
    return ChatControllerRemoveConversation200ResponseToJSONTyped(json, false);
}

export function ChatControllerRemoveConversation200ResponseToJSONTyped(value?: ChatControllerRemoveConversation200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

