/* tslint:disable */
/* eslint-disable */
/**
 * Chat API
 * Multi-turn conversation API built with LangChain and LangGraph. This API maintains conversation history using LangGraph\'s MemorySaver, allowing for contextual multi-turn conversations. The assistant has access to user information tools for personalization.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatRequestDto
 */
export interface ChatRequestDto {
    /**
     * The message from the user
     * @type {string}
     * @memberof ChatRequestDto
     */
    message: string;
    /**
     * The name of the user sending the message. Used for personalization.
     * @type {string}
     * @memberof ChatRequestDto
     */
    user: string;
    /**
     * UUID identifying the conversation thread. Use the same ID for all messages in a conversation to maintain context.
     * @type {string}
     * @memberof ChatRequestDto
     */
    conversationId: string;
}

/**
 * Check if a given object implements the ChatRequestDto interface.
 */
export function instanceOfChatRequestDto(value: object): value is ChatRequestDto {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('conversationId' in value) || value['conversationId'] === undefined) return false;
    return true;
}

export function ChatRequestDtoFromJSON(json: any): ChatRequestDto {
    return ChatRequestDtoFromJSONTyped(json, false);
}

export function ChatRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'user': json['user'],
        'conversationId': json['conversationId'],
    };
}

export function ChatRequestDtoToJSON(json: any): ChatRequestDto {
    return ChatRequestDtoToJSONTyped(json, false);
}

export function ChatRequestDtoToJSONTyped(value?: ChatRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'user': value['user'],
        'conversationId': value['conversationId'],
    };
}

