/* tslint:disable */
/* eslint-disable */
/**
 * Chat API
 * Multi-turn conversation API built with LangChain and LangGraph. This API maintains conversation history using LangGraph\'s MemorySaver, allowing for contextual multi-turn conversations. The assistant has access to user information tools for personalization.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewChatRequestDto
 */
export interface NewChatRequestDto {
    /**
     * The message from the user to start a new conversation
     * @type {string}
     * @memberof NewChatRequestDto
     */
    message: string;
    /**
     * The name of the user sending the message. Used for personalization.
     * @type {string}
     * @memberof NewChatRequestDto
     */
    user: string;
}

/**
 * Check if a given object implements the NewChatRequestDto interface.
 */
export function instanceOfNewChatRequestDto(value: object): value is NewChatRequestDto {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function NewChatRequestDtoFromJSON(json: any): NewChatRequestDto {
    return NewChatRequestDtoFromJSONTyped(json, false);
}

export function NewChatRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewChatRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'user': json['user'],
    };
}

export function NewChatRequestDtoToJSON(json: any): NewChatRequestDto {
    return NewChatRequestDtoToJSONTyped(json, false);
}

export function NewChatRequestDtoToJSONTyped(value?: NewChatRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'user': value['user'],
    };
}

