/* tslint:disable */
/* eslint-disable */
/**
 * E-commerce Assistant API
 * Conversational e-commerce assistant API built with LangChain. Features semantic product search and category browsing with multi-turn memory.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ContinueConversationRequestDto,
  ConversationResponseDto,
  EcommerceAssistantControllerRemoveConversation200Response,
  NewConversationRequestDto,
} from '../models/index';
import {
    ContinueConversationRequestDtoFromJSON,
    ContinueConversationRequestDtoToJSON,
    ConversationResponseDtoFromJSON,
    ConversationResponseDtoToJSON,
    EcommerceAssistantControllerRemoveConversation200ResponseFromJSON,
    EcommerceAssistantControllerRemoveConversation200ResponseToJSON,
    NewConversationRequestDtoFromJSON,
    NewConversationRequestDtoToJSON,
} from '../models/index';

export interface EcommerceAssistantControllerContinueConversationRequest {
    conversationId: string;
    continueConversationRequestDto: ContinueConversationRequestDto;
}

export interface EcommerceAssistantControllerCreateConversationRequest {
    newConversationRequestDto: NewConversationRequestDto;
}

export interface EcommerceAssistantControllerRemoveConversationRequest {
    conversationId: string;
}

/**
 * EcommerceAssistantApi - interface
 * 
 * @export
 * @interface EcommerceAssistantApiInterface
 */
export interface EcommerceAssistantApiInterface {
    /**
     * Send follow-up messages using the conversationId from the initial request
     * @summary Continue an existing conversation
     * @param {string} conversationId The conversation ID returned from the initial request
     * @param {ContinueConversationRequestDto} continueConversationRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EcommerceAssistantApiInterface
     */
    ecommerceAssistantControllerContinueConversationRaw(requestParameters: EcommerceAssistantControllerContinueConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationResponseDto>>;

    /**
     * Send follow-up messages using the conversationId from the initial request
     * Continue an existing conversation
     */
    ecommerceAssistantControllerContinueConversation(requestParameters: EcommerceAssistantControllerContinueConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationResponseDto>;

    /**
     * Create a new conversation with the e-commerce assistant. Ask about products or shop categories.
     * @summary Start a new e-commerce conversation
     * @param {NewConversationRequestDto} newConversationRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EcommerceAssistantApiInterface
     */
    ecommerceAssistantControllerCreateConversationRaw(requestParameters: EcommerceAssistantControllerCreateConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationResponseDto>>;

    /**
     * Create a new conversation with the e-commerce assistant. Ask about products or shop categories.
     * Start a new e-commerce conversation
     */
    ecommerceAssistantControllerCreateConversation(requestParameters: EcommerceAssistantControllerCreateConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationResponseDto>;

    /**
     * Delete conversation and its history from memory
     * @summary Remove a conversation
     * @param {string} conversationId The conversation ID to delete
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EcommerceAssistantApiInterface
     */
    ecommerceAssistantControllerRemoveConversationRaw(requestParameters: EcommerceAssistantControllerRemoveConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EcommerceAssistantControllerRemoveConversation200Response>>;

    /**
     * Delete conversation and its history from memory
     * Remove a conversation
     */
    ecommerceAssistantControllerRemoveConversation(requestParameters: EcommerceAssistantControllerRemoveConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EcommerceAssistantControllerRemoveConversation200Response>;

}

/**
 * 
 */
export class EcommerceAssistantApi extends runtime.BaseAPI implements EcommerceAssistantApiInterface {

    /**
     * Send follow-up messages using the conversationId from the initial request
     * Continue an existing conversation
     */
    async ecommerceAssistantControllerContinueConversationRaw(requestParameters: EcommerceAssistantControllerContinueConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationResponseDto>> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling ecommerceAssistantControllerContinueConversation().'
            );
        }

        if (requestParameters['continueConversationRequestDto'] == null) {
            throw new runtime.RequiredError(
                'continueConversationRequestDto',
                'Required parameter "continueConversationRequestDto" was null or undefined when calling ecommerceAssistantControllerContinueConversation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/ecommerce-assistant/{conversationId}`;
        urlPath = urlPath.replace(`{${"conversationId"}}`, encodeURIComponent(String(requestParameters['conversationId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ContinueConversationRequestDtoToJSON(requestParameters['continueConversationRequestDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConversationResponseDtoFromJSON(jsonValue));
    }

    /**
     * Send follow-up messages using the conversationId from the initial request
     * Continue an existing conversation
     */
    async ecommerceAssistantControllerContinueConversation(requestParameters: EcommerceAssistantControllerContinueConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationResponseDto> {
        const response = await this.ecommerceAssistantControllerContinueConversationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new conversation with the e-commerce assistant. Ask about products or shop categories.
     * Start a new e-commerce conversation
     */
    async ecommerceAssistantControllerCreateConversationRaw(requestParameters: EcommerceAssistantControllerCreateConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConversationResponseDto>> {
        if (requestParameters['newConversationRequestDto'] == null) {
            throw new runtime.RequiredError(
                'newConversationRequestDto',
                'Required parameter "newConversationRequestDto" was null or undefined when calling ecommerceAssistantControllerCreateConversation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/ecommerce-assistant`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NewConversationRequestDtoToJSON(requestParameters['newConversationRequestDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConversationResponseDtoFromJSON(jsonValue));
    }

    /**
     * Create a new conversation with the e-commerce assistant. Ask about products or shop categories.
     * Start a new e-commerce conversation
     */
    async ecommerceAssistantControllerCreateConversation(requestParameters: EcommerceAssistantControllerCreateConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConversationResponseDto> {
        const response = await this.ecommerceAssistantControllerCreateConversationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete conversation and its history from memory
     * Remove a conversation
     */
    async ecommerceAssistantControllerRemoveConversationRaw(requestParameters: EcommerceAssistantControllerRemoveConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EcommerceAssistantControllerRemoveConversation200Response>> {
        if (requestParameters['conversationId'] == null) {
            throw new runtime.RequiredError(
                'conversationId',
                'Required parameter "conversationId" was null or undefined when calling ecommerceAssistantControllerRemoveConversation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/ecommerce-assistant/{conversationId}`;
        urlPath = urlPath.replace(`{${"conversationId"}}`, encodeURIComponent(String(requestParameters['conversationId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EcommerceAssistantControllerRemoveConversation200ResponseFromJSON(jsonValue));
    }

    /**
     * Delete conversation and its history from memory
     * Remove a conversation
     */
    async ecommerceAssistantControllerRemoveConversation(requestParameters: EcommerceAssistantControllerRemoveConversationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EcommerceAssistantControllerRemoveConversation200Response> {
        const response = await this.ecommerceAssistantControllerRemoveConversationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
